language: python
python:
  - "3.6"
cache: pip

install:
  - pip install -I regression_model --find-links http://house-price-regression-package.s3-website-us-west-1.amazonaws.com/regression_model/regression_model-0.1.0.tar.gz
script:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - python packages/regression_model/setup.py sdist
  - aws s3 cp packages/regression_model/dist/regression_model-0.1.0.tar.gz s3://house-price-regression-package/regression/
  - python packages/regression_model/regression_model/train_pipeline.py
  - pytest packages/regression_model/tests/test_predict.py
