language: python
python:
   - "3.6"
cache: pip
install:
   - pip install -r packages/regression_model/requirements.txt
script:
   - python packages/regression_model/regression_model/train_pipeline.py
   - pytest packages/regression_model/tests/test_predict.py
