language: python
python:
  - "3.6"
cache: pip
script:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip -qq awscliv2.zip
  - sudo ./aws/install
  - cd packages/regression_model
  - python setup.py sdist
  - python regression_model/train_pipeline.py
  - python -m pytest tests
  - aws s3 cp ./dist/regression_model-0.1.0.tar.gz s3://house-price-regression-package/
